dist: xenial

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

env:
    - secure: "KUX/tUyFdlFU8GNxCjU5h/83v+caIx9UaxD8Zknm0mqJfxInwa0AqicoqToefLGAYL/Bf9igVho5SXiORgNkKBpt6eRvdy2T05xH2IZQwteEIIUfXxhi5k8nAMqNrefFANJfTdUsQ1u0YbXZgKgDgIYR4fjCt3vlp/svMyRCaJE5HTuFHD4I5fJTQOd7heOpugP2hvGNOILjSW9H6BVpTKkeZjnQsMGsQQbfUAYsWD7xsP1enoSMrVILlPtW1uaXHxkNEbQ5dNoiC0zz5hqG0T/LIBIYWjePa77N4EP8upTFmQIdAc+2rQH1lQhb+ectYCjTc3g+amHCb+tbWfAb+LP4leqGleD9lAPZLUnz42INeBncsoZZgr7arqw+qXDnQDJy86C333PubhsaWhs4KePzGznqmnj7d97T5iv6Cv1QkJzj13OUC/mGwfZBLA/mzX2kJWu785DCzXlWgu77pq3ocIBCEFJ5qMq8O9GdzPMou5Vlw4B26zZ3CwEU/Ghro9F9fmBVlanMhQiUjwf2tn67pjpqRnYVnLhKN3Ir8MaXi+wLvil3f5ZXY9mBLk/GTB5Ibh5ydGGomH+g7OWZy6ylNnc/uQm7wy5hlHOdXrscKMn53wkR9v12hrH90u1XMJ0WW4eRHiLl66lNln9RhnJUpr9/1DEALmiy2jFQTrQ="

_shared_job: &shared_job
  before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install
  script:
    - vendor/bin/phpunit

jobs:
  include:
    - stage: "Smoke Test"
      php: "7.2"
      before_script: composer install
      script: vendor/bin/phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 7.0 --ignore="vendor,*.js,*.min.css"
    - stage: "Unit Test"
      php: "7.0"
      env:
        - WP_VERSION=latest
      <<: *shared_job
      after_success:
        - travis_retry php vendor/bin/php-coveralls
    - stage: "Unit Test"
      php: "7.1"
      env:
        - WP_VERSION=latest
      <<: *shared_job
    - stage: "Unit Test"
      php: "7.2"
      env:
      - WP_VERSION=latest
      <<: *shared_job
    - stage: "Unit Test"
      php: "7.3"
      env:
      - WP_VERSION=latest
      <<: *shared_job
    - stage: "Coverage"
      php: "7.2"
      env:
        - WP_VERSION=latest
      before_script:
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        - composer install
      script:
        - mkdir -p build/logs
        - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      after_success:
        - travis_retry php vendor/bin/php-coveralls
    - stage: "Deployment to WP SVN (tag only)"
      php: "7.0"
      env:
          - WP_VERSION=latest
      script: skip
      before_deploy:
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        - composer install
      deploy:
        script: sh bin/commit-svn $TRAVIS_TAG --stable > /dev/null
        provider: script
        cleanup: false
        on:
          tags: true