dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest CODECOV=1
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer install
    fi

script:
  - mkdir -p build/logs
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
        if [[ -z "$CODECOV" ]] ; then
            vendor/bin/phpunit
        else
            vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        fi
    fi

after_success:
  - travis_retry php vendor/bin/php-coveralls